CREATE TABLE IF NOT EXISTS papers (
  id TEXT PRIMARY KEY,
  category TEXT,
  week TEXT,
  recorder TEXT,
  readDate TEXT,
  shared TEXT,
  relevance REAL DEFAULT 0,
  novelty REAL DEFAULT 0,
  evidence REAL DEFAULT 0,
  inspiration REAL DEFAULT 0,
  reproducibility REAL DEFAULT 0,
  title TEXT,
  source TEXT,
  link TEXT,
  direction TEXT,
  oneSentence TEXT,
  authors TEXT,
  task TEXT,
  motivation TEXT,
  dataset TEXT,
  platform TEXT,
  signalAnalysis TEXT,
  methodOverview TEXT,
  methodDetails TEXT,
  trainFlow TEXT,
  hardware TEXT,
  baselines TEXT,
  metrics TEXT,
  overallResults TEXT,
  coreEffect TEXT,
  ablation TEXT,
  inferenceSpeed TEXT,
  innovation1 TEXT,
  innovation2 TEXT,
  innovation3 TEXT,
  innovation4 TEXT,
  inspirationNote TEXT,
  limitations TEXT,
  newIdeas TEXT,
  created_at TEXT,
  updated_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_papers_updated_at ON papers(updated_at);
CREATE INDEX IF NOT EXISTS idx_papers_category ON papers(category);
CREATE INDEX IF NOT EXISTS idx_papers_shared ON papers(shared);
